Epoch 1/10
Entrenamiento - Loss: 1211.3137, Accuracy: 0.8946
Validaci√≥n - Loss: 122.1690, Accuracy: 0.9642
Epoch 2/10
Entrenamiento - Loss: 401.1269, Accuracy: 0.9710
Validaci√≥n - Loss: 117.0434, Accuracy: 0.9667
Epoch 3/10
Entrenamiento - Loss: 293.4628, Accuracy: 0.9800
Validaci√≥n - Loss: 70.1779, Accuracy: 0.9817
Epoch 4/10
Entrenamiento - Loss: 201.6057, Accuracy: 0.9858
Validaci√≥n - Loss: 99.5088, Accuracy: 0.9817
Epoch 5/10
Entrenamiento - Loss: 137.3587, Accuracy: 0.9921
Validaci√≥n - Loss: 123.8412, Accuracy: 0.9725
Epoch 6/10
Entrenamiento - Loss: 146.9780, Accuracy: 0.9904
Validaci√≥n - Loss: 73.8009, Accuracy: 0.9808
Epoch 7/10
Entrenamiento - Loss: 92.2358, Accuracy: 0.9931
Validaci√≥n - Loss: 73.0072, Accuracy: 0.9833
Epoch 8/10
Entrenamiento - Loss: 99.5972, Accuracy: 0.9927
Validaci√≥n - Loss: 76.0269, Accuracy: 0.9833
Epoch 9/10
Entrenamiento - Loss: 50.2715, Accuracy: 0.9977
Validaci√≥n - Loss: 119.3003, Accuracy: 0.9800
Epoch 10/10
Entrenamiento - Loss: 43.9325, Accuracy: 0.9977
Validaci√≥n - Loss: 98.1406, Accuracy: 0.9833
‚úÖ ATTENTION POOLING completado:
   üìà Accuracy: 0.9890
   üìà F1-Score: 0.9921
üîç Generando visualizaciones de mapas de atenci√≥n REALES...
/tmp/ipykernel_2495682/1178334238.py:90: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(model_path, map_location=device)
‚ùå Error cargando modelo: 'collections.OrderedDict' object has no attribute 'eval'
