2025-03-13 13:05:01,904 INFO    MainThread:3850153 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/wandb/run-20250313_130501-s2v7ccnd/logs/debug.log
2025-03-13 13:05:01,904 INFO    MainThread:3850153 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/wandb/run-20250313_130501-s2v7ccnd/logs/debug-internal.log
2025-03-13 13:05:01,904 INFO    MainThread:3850153 [wandb_init.py:init():761] calling init triggers
2025-03-13 13:05:01,904 INFO    MainThread:3850153 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset_name': 'rsna-features_resnet18', 'num_epochs': 5, 'learning_rate': 0.001, 'batch_size': 1, 'val_prop': 0.15, 'seed': 42, 'use_inst_distances': False, 'adj_mat_mode': 'relative', 'pooling_type': 'mean', '_wandb': {}}
2025-03-13 13:05:01,904 INFO    MainThread:3850153 [wandb_init.py:init():784] starting backend
2025-03-13 13:05:01,904 INFO    MainThread:3850153 [wandb_init.py:init():788] sending inform_init request
2025-03-13 13:05:01,906 INFO    MainThread:3850153 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-13 13:05:01,907 INFO    MainThread:3850153 [wandb_init.py:init():803] backend started and connected
2025-03-13 13:05:01,909 INFO    MainThread:3850153 [wandb_init.py:init():896] updated telemetry
2025-03-13 13:05:01,920 INFO    MainThread:3850153 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-13 13:05:02,343 INFO    MainThread:3850153 [wandb_init.py:init():995] starting run threads in backend
2025-03-13 13:05:02,527 INFO    MainThread:3850153 [wandb_run.py:_console_start():2377] atexit reg
2025-03-13 13:05:02,527 INFO    MainThread:3850153 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-13 13:05:02,528 INFO    MainThread:3850153 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-13 13:05:02,528 INFO    MainThread:3850153 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-13 13:05:02,529 INFO    MainThread:3850153 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-13 13:05:14,990 INFO    MainThread:3850153 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'val_confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'val_confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-03-13 13:05:18,852 INFO    MainThread:3850153 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'val_confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'val_confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-03-13 13:05:22,722 INFO    MainThread:3850153 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'val_confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'val_confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-03-13 13:05:26,584 INFO    MainThread:3850153 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'val_confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'val_confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-03-13 13:05:30,447 INFO    MainThread:3850153 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'val_confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'val_confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-03-13 13:05:31,301 INFO    MainThread:3850153 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-03-13 13:05:31,508 WARNING MsgRouterThr:3850153 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-13 13:05:31,510 INFO    MsgRouterThr:3850153 [mailbox.py:close():115] Closing mailbox, abandoning 4 handles.
