2025-05-23 12:18:20,187 INFO    MainThread:2461414 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121820-qghjw4qt/logs/debug.log
2025-05-23 12:18:20,187 INFO    MainThread:2461414 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121820-qghjw4qt/logs/debug-internal.log
2025-05-23 12:18:20,187 INFO    MainThread:2461414 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f3d112bc710>
2025-05-23 12:18:20,187 INFO    MainThread:2461414 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:18:20,187 INFO    MainThread:2461414 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 10, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'attention', 'seed': 1, '_wandb': {}}
2025-05-23 12:18:20,187 INFO    MainThread:2461414 [wandb_init.py:init():784] starting backend
2025-05-23 12:18:20,187 INFO    MainThread:2461414 [wandb_init.py:init():788] sending inform_init request
2025-05-23 12:18:20,187 INFO    MainThread:2461414 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-23 12:18:20,188 INFO    MainThread:2461414 [wandb_init.py:init():803] backend started and connected
2025-05-23 12:18:20,189 INFO    MainThread:2461414 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-05-23 12:18:20,189 INFO    MainThread:2461414 [wandb_init.py:init():896] updated telemetry
2025-05-23 12:18:20,193 INFO    MainThread:2461414 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-05-23 12:18:20,583 INFO    MainThread:2461414 [wandb_init.py:init():995] starting run threads in backend
2025-05-23 12:18:20,642 INFO    MainThread:2461414 [wandb_run.py:_console_start():2377] atexit reg
2025-05-23 12:18:20,643 INFO    MainThread:2461414 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-05-23 12:18:20,643 INFO    MainThread:2461414 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-05-23 12:18:20,643 INFO    MainThread:2461414 [wandb_run.py:_redirect():2317] Redirects installed.
2025-05-23 12:18:20,643 INFO    MainThread:2461414 [wandb_init.py:init():1037] run started, returning control to user process
2025-05-23 12:18:43,959 WARNING MsgRouterThr:2461414 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-23 12:18:43,970 INFO    MsgRouterThr:2461414 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-05-23 12:18:44,591 INFO    MainThread:2461414 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-05-23 12:18:44,591 INFO    MainThread:2461414 [wandb_init.py:_pause_backend():564] pausing backend
2025-05-23 12:18:53,255 INFO    MainThread:2461414 [wandb_init.py:_resume_backend():569] resuming backend
2025-05-23 12:18:53,456 INFO    MainThread:2461414 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-05-23 12:18:53,456 INFO    MainThread:2461414 [wandb_init.py:_pause_backend():564] pausing backend
