2025-03-14 09:41:04,493 INFO    MainThread:3891067 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250314_094104-1kvnje00/logs/debug.log
2025-03-14 09:41:04,493 INFO    MainThread:3891067 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250314_094104-1kvnje00/logs/debug-internal.log
2025-03-14 09:41:04,494 INFO    MainThread:3891067 [wandb_init.py:init():761] calling init triggers
2025-03-14 09:41:04,494 INFO    MainThread:3891067 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset_name': 'rsna-features_resnet18', 'num_epochs': 50, 'learning_rate': 0.001, 'batch_size': 1, 'val_prop': 0.2, 'seed': 42, 'use_inst_distances': False, 'adj_mat_mode': 'relative', '_wandb': {}}
2025-03-14 09:41:04,494 INFO    MainThread:3891067 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-14 09:41:28,160 INFO    MainThread:3891067 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'val_confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'val_confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-03-14 09:41:34,059 INFO    MainThread:3891067 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'val_confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'val_confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-03-14 09:41:35,625 WARNING MsgRouterThr:3891067 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-14 09:41:35,664 INFO    MsgRouterThr:3891067 [mailbox.py:close():115] Closing mailbox, abandoning 4 handles.
2025-03-14 09:41:35,818 INFO    MainThread:3891067 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 09:41:35,818 INFO    MainThread:3891067 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 09:43:28,565 INFO    MainThread:3891067 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 09:43:29,183 INFO    MainThread:3891067 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250314_094329-n3s68zw3/logs/debug.log
2025-03-14 09:43:29,183 INFO    MainThread:3891067 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250314_094329-n3s68zw3/logs/debug-internal.log
2025-03-14 09:43:29,183 INFO    MainThread:3891067 [wandb_init.py:init():761] calling init triggers
2025-03-14 09:43:29,184 INFO    MainThread:3891067 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset_name': 'panda-patches_512_preset-features_UNI', 'input_feature_dim': 1024, 'feature_dim': 128, 'num_epochs': 10, 'learning_rate': 0.001, 'batch_size': 1, 'val_prop': 0.2, 'seed': 42, 'use_inst_distances': False, 'adj_mat_mode': 'relative', '_wandb': {}}
2025-03-14 09:43:29,184 INFO    MainThread:3891067 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-14 09:43:43,050 INFO    MainThread:3891067 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 09:43:43,051 INFO    MainThread:3891067 [wandb_init.py:_pause_backend():564] pausing backend
